#!/usr/bin/env sh

if ! git rev-parse --git-dir >/dev/null; then
	exit 1
fi

print_help() (
	cat <<-EOF
	usage: git repo-status [general options]
	   or: git repo-status -h

	  -h
	      Print this help screen.

	General options:

	  -r <remote>
	      Specifies the name of the remote used to gather
	      and print information. If not given, the following
	      guess is performed:
	        1. If there is only one remote, use that.
	        2. If there is more than one remote,
	           and origin is among them, use origin.
	        3. Otherwise, no remote is chosen.

	  -t <branch>
	      Specifies the target branch, i.e. the branch to which
	      the current branch will be merged. If not given,
	      <remote>/HEAD is used.

	  -w
	        Use wide mode, printing output in columns.
EOF
)

while getopts t:r:wh flag; do
	case "${flag}" in
	h) print_help; exit ;;
	r) REMOTE="${OPTARG}" ;;
	t) merge_target="${OPTARG}" ;;
	w) wide="true" ;;
	*) exit 1 ;;
	esac
done

# clear screen for interactive use
test -t 1 && clear -x

# shellcheck source=libstatus.sh
. "$(dirname "${0}")/libstatus.sh"

init

if test -z "${wide}"; then
	print_tree_status

	print_rebase_summary

	print_current_and_upstream
	print_current_and_target "${merge_target}"

	if are_there_submodules; then
		print_submodule_status
		print_submodule_summary
	fi

	print_stash
	print_worktree_list
else
	left="$(mktemp)"
	right="$(mktemp)"
	{
		print_tree_status
		print_current_and_upstream
	} >"${left}"
	{
		print_worktree_list
		print_current_and_target "${merge_target}"
	} >"${right}"

	columnize "${left}" "${right}"

	if are_there_submodules; then
		print_submodule_status >"${left}"
		print_submodule_summary >"${right}"
		columnize "${left}" "${right}"
	fi

	rm "${left}" "${right}"

	print_stash
fi

print_untracked_hint
print_intent_to_add_hint
print_mistracking_hint
print_rebase_lost_merges_hint
